slug = "postbin-3"
title = "Postbin 3"
author = "defund"
value = 50
description = """Finally! I've made the ultimate filter, the one I was trying to create all along. *THIS* one is unbreakable.

The admin has a cookie containing the flag on this [postbin](http://postbin3.acmcyber.com:10000). Report links you want the admin to visit [here](http://acmcyber.com:10001)."""
tags = ["xss"]
files = []
flag = "flag{what_did_you_u&#0115e}"
enabled = true
